### ISSUE TITLE
レビュー依頼用issue

### ISSUE THREAD

**Issue by Yoshihito-0930** [Yoshihito-0930/ride_finder#82]
## 各種情報
サービス名
RideFinder

サービスURL
https://ride-finder.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 行き先検索, マップ表示(Google Maps APIを利用)
- [ ] 条件検索機能(カテゴリや距離時間の指定)

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください

ユーザー登録機能とログイン機能はOAuth認証を使って実装しました。
LINEアカウントとGoogleアカウントでログイン出来るようになっています。

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

トップページ
[![Image from Gyazo](https://i.gyazo.com/5fcda5caf723d2ceaf56e2615e424048.png)](https://gyazo.com/5fcda5caf723d2ceaf56e2615e424048)

ログイン画面
画面右上のログインからログイン画面にページが遷移します。(ログイン後の機能は現在ありません)
[![Image from Gyazo](https://i.gyazo.com/f7b13e7f4f34a71c554bf50eadcdcaa7.png)](https://gyazo.com/f7b13e7f4f34a71c554bf50eadcdcaa7)

検索機能
画面上部の `ツーリングスポットを探す` でモーダルが開かれます。
[![Image from Gyazo](https://i.gyazo.com/73b90aa3bdc119d9970d6590111d033c.png)](https://gyazo.com/73b90aa3bdc119d9970d6590111d033c)

  選択内容によって現在地から探す条件が変わります。
 `距離` 選択の場合
[![Image from Gyazo](https://i.gyazo.com/6f76e8922694c7df4b861ec90007ff2b.png)](https://gyazo.com/6f76e8922694c7df4b861ec90007ff2b)
 `時間` 選択の場合
[![Image from Gyazo](https://i.gyazo.com/722eced23d0ef55a3e069dacbdb49853.png)](https://gyazo.com/722eced23d0ef55a3e069dacbdb49853)

検索結果一覧画面
google map上に該当候補地のマーカーが表示され、検索結果一覧に候補地の情報があります。
[![Image from Gyazo](https://i.gyazo.com/8fbe159e4209f56d8d7833d66c6ee6d1.jpg)](https://gyazo.com/8fbe159e4209f56d8d7833d66c6ee6d1)

使用イメージ
候補地を見て行ってみたい場所があれば「一般道」「無料高速道路」「有料道路」のいずれかのルートを押下するとgoogle mapの経路選択画面に遷移します。
[![Image from Gyazo](https://i.gyazo.com/3f4365f62a9ba856ccfd4afa07e87919.png)](https://gyazo.com/3f4365f62a9ba856ccfd4afa07e87919)
[![Image from Gyazo](https://i.gyazo.com/5c874ed17447285b53da1f58f9ece494.gif)](https://gyazo.com/5c874ed17447285b53da1f58f9ece494)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by Yoshihito-0930** [comment]
確認ありがとうございました。
このイシューはクローズさせてもらいます。
